CUR_DRIVERS_PATH := $(call get_relative_path)

include $(CUR_DRIVERS_PATH)/audio/Makefile
include $(CUR_DRIVERS_PATH)/fingerprint/Makefile
include $(CUR_DRIVERS_PATH)/flash/Makefile
include $(CUR_DRIVERS_PATH)/led/Makefile
include $(CUR_DRIVERS_PATH)/usb2otg/Makefile
include $(CUR_DRIVERS_PATH)/videoin/Makefile
include $(CUR_DRIVERS_PATH)/display/Makefile
